const PASSAGE_01 = {
  meta: {
    id: 'bosques',
    title: 'Los bosques del norte de Canadá',
    level: 'B2',
    topic: '자연·환경'
  },

  paragraphs_es: [
    'Los bosques boreales del norte de Canadá, también conocidos como la taiga, constituyen uno de los ecosistemas más extensos del planeta. Estos vastos territorios albergan una biodiversidad extraordinaria, donde conviven especies animales y vegetales que han logrado adaptarse a las condiciones climáticas extremas de la región.',
    'El clima de estas zonas se caracteriza por inviernos prolongados y veranos breves pero intensos. Las temperaturas pueden descender hasta los cuarenta grados bajo cero durante los meses más fríos, mientras que en verano el mercurio asciende moderadamente. Esta variación térmica tan pronunciada exige que tanto la flora como la fauna desarrollen mecanismos de supervivencia únicos.',
    'Entre los árboles predominantes se encuentran el abeto, el pino y el abedul. Estos árboles robustos han evolucionado para soportar el peso de la nieve y sobrevivir con escasa luz solar durante el invierno. Sus raíces superficiales se extienden horizontalmente para aprovechar los nutrientes disponibles en el suelo delgado y frecuentemente helado.',
    'La fauna de la taiga canadiense es igualmente fascinante. El alce, el oso negro y el lobo gris son depredadores y herbívoros que comparten este hábitat. Aves migratorias como el ganso canadiense atraviesan estos bosques durante sus viajes estacionales. Además, mamíferos pequeños como la ardilla roja y el castor desempeñan un papel crucial en el mantenimiento del equilibrio ecológico.',
    'Sin embargo, estos ecosistemas enfrentan amenazas crecientes debido al cambio climático y la deforestación. El aumento de las temperaturas provoca el deshielo del permafrost, alterando los patrones hidrológicos de la región. La explotación maderera también ha reducido considerablemente la extensión de estos bosques, poniendo en riesgo la supervivencia de numerosas especies.',
    'Las comunidades indígenas que habitan estas regiones desde tiempos ancestrales han desarrollado una relación profunda con el bosque. Sus conocimientos tradicionales sobre la flora y la fauna locales resultan invaluables para la conservación del medio ambiente. Actualmente, muchos proyectos de investigación colaboran con estas comunidades para preservar tanto el patrimonio cultural como el natural.'
  ],

  paragraphs_ko: [
    '캐나다 북부의 보레알 숲은 타이가라고도 알려져 있으며, 지구에서 가장 넓은 생태계 중 하나를 구성합니다. 이 드넓은 영토는 놀라운 생물다양성을 품고 있으며, 이 지역의 극한 기후 조건에 적응한 동물·식물 종들이 공존합니다.',
    '이 지역의 기후는 길고 추운 겨울과 짧지만 강렬한 여름을 특징으로 합니다. 가장 추운 달에는 기온이 영하 40도까지 내려갈 수 있으며, 여름에는 수은주가 적당히 올라갑니다. 이처럼 뚜렷한 온도 변화는 식물군과 동물군 모두가 독특한 생존 메커니즘을 발전시킬 것을 요구합니다.',
    '주요 나무로는 전나무, 소나무, 자작나무가 있습니다. 이 튼튼한 나무들은 눈의 무게를 견디고 겨울 동안 일조량이 부족해도 생존하도록 진화했습니다. 이들의 얕은 뿌리는 얇고 자주 얼어붙는 토양에서 영양분을 활용하기 위해 수평으로 뻗어 있습니다.',
    '캐나다 타이가의 동물군도 마찬가지로 매혹적입니다. 엘크, 흑곰, 회색 늑대는 이 서식지를 공유하는 포식자이자 초식동물입니다. 캐나다 기러기 같은 철새들은 계절 이동 중에 이 숲을 가로지릅니다. 또한 붉은 다람쥐와 비버 같은 소형 포유류들은 생태계 균형 유지에 중요한 역할을 담당합니다.',
    '그러나 이 생태계들은 기후변화와 삼림 벌채로 인해 점점 커지는 위협에 직면하고 있습니다. 기온 상승은 영구 동토층의 해빙을 유발하여 이 지역의 수문학적 패턴을 변화시킵니다. 목재 채취 역시 이 숲의 범위를 상당히 줄여 수많은 종들의 생존을 위험에 빠뜨리고 있습니다.',
    '먼 옛날부터 이 지역에 거주해 온 원주민 공동체들은 숲과 깊은 관계를 발전시켜 왔습니다. 지역 동식물에 관한 그들의 전통 지식은 환경 보전에 매우 귀중합니다. 현재 많은 연구 프로젝트들이 문화적 유산과 자연 유산을 모두 보존하기 위해 이 공동체들과 협력하고 있습니다.'
  ],

  vocab: [
    // NOUNS
    {id:'bosque',        t:'noun', w:'bosque',              m:'숲',           ee:'El bosque es muy denso y verde.',                ek:'그 숲은 매우 울창하고 초록빛이다.',        ant:'desierto (사막)',          frm:'bosques (복수)'},
    {id:'ecosistema',    t:'noun', w:'ecosistema',           m:'생태계',        ee:'El ecosistema marino está en peligro.',          ek:'해양 생태계가 위기에 처해 있다.',          ant:'-',                        frm:'ecosistemas (복수)'},
    {id:'biodiversidad', t:'noun', w:'biodiversidad',        m:'생물다양성',    ee:'La biodiversidad del Amazonas es única.',        ek:'아마존의 생물다양성은 독특하다.',          ant:'-',                        frm:'-'},
    {id:'clima',         t:'noun', w:'clima',                m:'기후',          ee:'El clima tropical es cálido y húmedo.',          ek:'열대 기후는 따뜻하고 습하다.',            ant:'-',                        frm:'climas (복수)'},
    {id:'temperatura',   t:'noun', w:'temperatura',          m:'온도, 기온',    ee:'La temperatura bajó mucho anoche.',              ek:'어젯밤 기온이 많이 내려갔다.',            ant:'-',                        frm:'temperaturas (복수)'},
    {id:'invierno',      t:'noun', w:'invierno',             m:'겨울',          ee:'El invierno aquí dura seis meses.',              ek:'이곳의 겨울은 6개월 동안 계속된다.',      ant:'verano (여름)',             frm:'inviernos (복수)'},
    {id:'verano',        t:'noun', w:'verano',               m:'여름',          ee:'En verano hace mucho calor.',                    ek:'여름에는 매우 덥다.',                      ant:'invierno (겨울)',           frm:'veranos (복수)'},
    {id:'flora',         t:'noun', w:'flora',                m:'식물군',        ee:'La flora mediterránea es muy diversa.',          ek:'지중해 식물군은 매우 다양하다.',          ant:'fauna (동물군)',            frm:'-'},
    {id:'fauna',         t:'noun', w:'fauna',                m:'동물군',        ee:'La fauna australiana incluye el canguro.',       ek:'호주 동물군에는 캥거루가 포함된다.',      ant:'flora (식물군)',            frm:'-'},
    {id:'arbol',         t:'noun', w:'árbol',                m:'나무',          ee:'Ese árbol tiene cien años de antigüedad.',       ek:'저 나무는 수령이 100년이다.',              ant:'-',                        frm:'árboles (복수)'},
    {id:'abeto',         t:'noun', w:'abeto',                m:'전나무',        ee:'El abeto es símbolo de la Navidad.',             ek:'전나무는 크리스마스의 상징이다.',          ant:'-',                        frm:'abetos (복수)'},
    {id:'pino',          t:'noun', w:'pino',                 m:'소나무',        ee:'El bosque huele a pino.',                        ek:'숲에서 소나무 향기가 난다.',              ant:'-',                        frm:'pinos (복수)'},
    {id:'abedul',        t:'noun', w:'abedul',               m:'자작나무',      ee:'El abedul tiene la corteza de color blanco.',    ek:'자작나무는 흰색 껍질을 가지고 있다.',    ant:'-',                        frm:'abedules (복수)'},
    {id:'raiz',          t:'noun', w:'raíz',                 m:'뿌리',          ee:'Las raíces del árbol son muy profundas.',        ek:'나무의 뿌리는 매우 깊다.',                ant:'-',                        frm:'raíces (복수)'},
    {id:'suelo',         t:'noun', w:'suelo',                m:'토양, 땅',      ee:'El suelo fértil es ideal para cultivar.',        ek:'비옥한 토양은 농사짓기에 이상적이다.',    ant:'cielo (하늘)',              frm:'suelos (복수)'},
    {id:'alce',          t:'noun', w:'alce',                 m:'엘크(큰사슴)', ee:'El alce es el animal más grande del bosque.',    ek:'엘크는 숲에서 가장 큰 동물이다.',        ant:'-',                        frm:'alces (복수)'},
    {id:'lobo',          t:'noun', w:'lobo',                 m:'늑대',          ee:'El lobo vive y caza en manada.',                 ek:'늑대는 무리를 지어 살고 사냥한다.',      ant:'-',                        frm:'lobos (복수)'},
    {id:'oso',           t:'noun', w:'oso',                  m:'곰',            ee:'El oso hiberna durante el invierno.',            ek:'곰은 겨울 동안 동면한다.',                ant:'-',                        frm:'osos (복수)'},
    {id:'ardilla',       t:'noun', w:'ardilla',              m:'다람쥐',        ee:'La ardilla guarda nueces para el invierno.',     ek:'다람쥐는 겨울을 위해 도토리를 모은다.',  ant:'-',                        frm:'ardillas (복수)'},
    {id:'castor',        t:'noun', w:'castor',               m:'비버',          ee:'El castor construye diques en el río.',          ek:'비버는 강에 댐을 만든다.',                ant:'-',                        frm:'castores (복수)'},
    {id:'amenaza',       t:'noun', w:'amenaza',              m:'위협',          ee:'El cambio climático es una gran amenaza.',       ek:'기후변화는 큰 위협이다.',                  ant:'protección (보호)',         frm:'amenazas (복수)'},
    {id:'deforestacion', t:'noun', w:'deforestación',        m:'삼림 벌채',     ee:'La deforestación destruye los ecosistemas.',    ek:'삼림 벌채는 생태계를 파괴한다.',          ant:'reforestación (재조림)',    frm:'-'},
    {id:'permafrost',    t:'noun', w:'permafrost',           m:'영구 동토층',   ee:'El permafrost se derrite por el calor.',         ek:'영구 동토층이 온난화로 녹고 있다.',      ant:'-',                        frm:'-'},
    {id:'comunidad',     t:'noun', w:'comunidad',            m:'공동체',        ee:'La comunidad se unió para ayudar.',              ek:'공동체가 힘을 합쳐 도왔다.',              ant:'individuo (개인)',          frm:'comunidades (복수)'},
    {id:'patrimonio',    t:'noun', w:'patrimonio',           m:'유산',          ee:'Este lugar es patrimonio de la humanidad.',      ek:'이 장소는 인류의 유산이다.',              ant:'-',                        frm:'patrimonios (복수)'},
    {id:'supervivencia', t:'noun', w:'supervivencia',        m:'생존',          ee:'Los instintos de supervivencia son fuertes.',   ek:'생존 본능은 강하다.',                      ant:'extinción (멸종)',          frm:'-'},
    // ADJECTIVES
    {id:'extenso',       t:'adj',  w:'extenso',              m:'광대한',        ee:'Es un territorio muy extenso.',                 ek:'그것은 매우 광대한 영토이다.',            ant:'reducido (좁은)',           frm:'extensa / extensos / extensas'},
    {id:'vasto',         t:'adj',  w:'vasto',                m:'드넓은',        ee:'Vivían en vastas llanuras.',                     ek:'그들은 드넓은 평원에서 살았다.',          ant:'reducido (좁은)',           frm:'vasta / vastos / vastas'},
    {id:'extraordinario',t:'adj',  w:'extraordinario',       m:'특별한, 놀라운', ee:'Tuvo un talento extraordinario.',               ek:'그는 놀라운 재능을 가졌다.',              ant:'ordinario (평범한)',        frm:'extraordinaria / extraordinarios'},
    {id:'prolongado',    t:'adj',  w:'prolongado',           m:'길어진, 오랜',  ee:'Sufrió una enfermedad prolongada.',              ek:'그는 오랜 병을 앓았다.',                  ant:'breve (짧은)',              frm:'prolongada / prolongados'},
    {id:'breve',         t:'adj',  w:'breve',                m:'짧은',          ee:'Fue una visita muy breve.',                      ek:'그것은 매우 짧은 방문이었다.',            ant:'prolongado (오랜)',         frm:'breve / breves'},
    {id:'pronunciado',   t:'adj',  w:'pronunciado',          m:'뚜렷한, 심한',  ee:'Hay una diferencia muy pronunciada.',            ek:'매우 뚜렷한 차이가 있다.',                ant:'leve (약한)',               frm:'pronunciada / pronunciados'},
    {id:'superficial',   t:'adj',  w:'superficial',          m:'표면의, 얕은',  ee:'Tiene un conocimiento superficial del tema.',    ek:'그는 그 주제에 대한 얕은 지식을 갖고 있다.', ant:'profundo (깊은)',      frm:'superficial / superficiales'},
    {id:'helado',        t:'adj',  w:'helado',               m:'얼어붙은',      ee:'El suelo estaba completamente helado.',          ek:'땅이 완전히 얼어붙어 있었다.',            ant:'derretido (녹은)',          frm:'helada / helados / heladas'},
    {id:'migratorio',    t:'adj',  w:'migratorio',           m:'이동하는, 철새의', ee:'Las aves migratorias llegan en primavera.',  ek:'철새들이 봄에 도착한다.',                ant:'sedentario (정착성)',       frm:'migratoria / migratorios'},
    {id:'ancestral',     t:'adj',  w:'ancestral',            m:'조상의',        ee:'Mantienen sus costumbres ancestrales.',          ek:'그들은 조상의 풍습을 유지하고 있다.',    ant:'moderno (현대의)',          frm:'ancestral / ancestrales'},
    {id:'invaluable',    t:'adj',  w:'invaluable',           m:'매우 귀중한',   ee:'Su experiencia es invaluable para el equipo.',   ek:'그의 경험은 팀에 매우 귀중하다.',        ant:'-',                        frm:'invaluable / invaluables'},
    // VERBS
    {id:'constituir',    t:'verb', w:'constituir',           m:'구성하다',      ee:'Estos elementos constituyen el sistema.',        ek:'이 요소들이 시스템을 구성한다.',          ant:'disolver (해체하다)',       frm:'constituyo, constituyes, constituye'},
    {id:'albergar',      t:'verb', w:'albergar',             m:'품다, 수용하다', ee:'Este refugio alberga cien animales.',            ek:'이 보호구역은 100마리 동물을 수용한다.', ant:'expulsar (쫓아내다)',       frm:'albergo, albergas, alberga'},
    {id:'convivir',      t:'verb', w:'convivir',             m:'공존하다',      ee:'Distintas culturas conviven en esta ciudad.',    ek:'다양한 문화가 이 도시에서 공존한다.',    ant:'competir (경쟁하다)',       frm:'convivo, convives, convive'},
    {id:'adaptarse',     t:'verb', w:'adaptarse',            m:'적응하다',      ee:'Los animales se adaptan al entorno.',            ek:'동물들은 환경에 적응한다.',              ant:'-',                        frm:'me adapto, te adaptas, se adapta'},
    {id:'caracterizarse',t:'verb', w:'caracterizarse',       m:'특징지어지다',  ee:'La región se caracteriza por el frío.',          ek:'그 지역은 추위로 특징지어진다.',          ant:'-',                        frm:'se caracteriza, se caracterizan'},
    {id:'descender',     t:'verb', w:'descender',            m:'내려가다',      ee:'La temperatura desciende en diciembre.',         ek:'기온이 12월에 내려간다.',                ant:'ascender (올라가다)',       frm:'desciendo, desciendes, desciende'},
    {id:'ascender',      t:'verb', w:'ascender',             m:'올라가다',      ee:'El mercurio asciende en verano.',                ek:'여름에 수은주가 올라간다.',              ant:'descender (내려가다)',      frm:'asciendo, asciendes, asciende'},
    {id:'exigir',        t:'verb', w:'exigir',               m:'요구하다',      ee:'El trabajo exige mucha dedicación.',             ek:'그 일은 많은 헌신을 요구한다.',          ant:'-',                        frm:'exijo, exiges, exige'},
    {id:'desarrollar',   t:'verb', w:'desarrollar',          m:'발전시키다',    ee:'Necesitamos desarrollar nuevas habilidades.',    ek:'우리는 새로운 능력을 발전시켜야 한다.', ant:'-',                        frm:'desarrollo, desarrollas, desarrolla'},
    {id:'soportar',      t:'verb', w:'soportar',             m:'견디다, 지탱하다', ee:'No puedo soportar el calor extremo.',        ek:'나는 극한의 더위를 견딜 수 없다.',      ant:'-',                        frm:'soporto, soportas, soporta'},
    {id:'sobrevivir',    t:'verb', w:'sobrevivir',           m:'생존하다',      ee:'Sobrevivió al grave accidente.',                 ek:'그는 심각한 사고에서 살아남았다.',        ant:'morir (죽다)',              frm:'sobrevivo, sobrevives, sobrevive'},
    {id:'extenderse',    t:'verb', w:'extenderse',           m:'뻗어나가다',    ee:'El desierto se extiende por kilómetros.',        ek:'사막이 수 킬로미터에 걸쳐 뻗어 있다.', ant:'reducirse (줄어들다)',      frm:'se extiende, se extienden'},
    {id:'aprovechar',    t:'verb', w:'aprovechar',           m:'활용하다',      ee:'Hay que aprovechar el tiempo libre.',            ek:'자유 시간을 잘 활용해야 한다.',          ant:'desperdiciar (낭비하다)',   frm:'aprovecho, aprovechas, aprovecha'},
    {id:'atravesar',     t:'verb', w:'atravesar',            m:'가로지르다',    ee:'Atravesamos el desierto en coche.',              ek:'우리는 차로 사막을 가로질렀다.',          ant:'-',                        frm:'atravieso, atraviesas, atraviesa'},
    {id:'desempenar',    t:'verb', w:'desempeñar',           m:'수행하다, 맡다', ee:'Desempeña un papel importante en el equipo.',   ek:'그는 팀에서 중요한 역할을 맡고 있다.', ant:'-',                        frm:'desempeño, desempeñas, desempeña'},
    {id:'enfrentar',     t:'verb', w:'enfrentar',            m:'직면하다',      ee:'Debemos enfrentar los desafíos del futuro.',     ek:'우리는 미래의 도전에 직면해야 한다.',   ant:'evitar (피하다)',           frm:'enfrento, enfrentas, enfrenta'},
    {id:'preservar',     t:'verb', w:'preservar',            m:'보존하다',      ee:'Debemos preservar el medio ambiente.',           ek:'우리는 환경을 보존해야 한다.',            ant:'destruir (파괴하다)',       frm:'preservo, preservas, preserva'},
    // EXPRESSIONS
    {id:'tambienconocidocomo',       t:'expr', w:'también conocido como',      m:'~로도 알려진',       ee:'Este lugar, también conocido como "El Paraíso", es precioso.', ek:'"낙원"으로도 알려진 이 장소는 아름답다.', ant:'-', frm:'-'},
    {id:'secaracterizapor',          t:'expr', w:'se caracteriza por',         m:'~를 특징으로 하다',  ee:'Esta región se caracteriza por sus bosques densos.',           ek:'이 지역은 울창한 숲을 특징으로 한다.',  ant:'-', frm:'-'},
    {id:'tantocomo',                 t:'expr', w:'tanto...como',               m:'~뿐만 아니라 ~도',   ee:'Tanto los animales como las plantas necesitan agua.',           ek:'동물뿐만 아니라 식물도 물이 필요하다.', ant:'-', frm:'-'},
    {id:'sinembargo',                t:'expr', w:'sin embargo',                m:'그러나, 하지만',      ee:'Estudié mucho; sin embargo, no aprobé.',                       ek:'열심히 공부했다; 하지만 합격하지 못했다.', ant:'por lo tanto (따라서)', frm:'-'},
    {id:'debidoa',                   t:'expr', w:'debido a',                   m:'~ 때문에',            ee:'Debido a la lluvia, cancelamos el picnic.',                    ek:'비 때문에 소풍을 취소했다.',           ant:'a pesar de (~에도 불구하고)', frm:'-'},
    {id:'poniendoenriesgo',          t:'expr', w:'poniendo en riesgo',         m:'위험에 빠뜨리면서',   ee:'Su decisión está poniendo en riesgo a la empresa.',            ek:'그의 결정이 회사를 위험에 빠뜨리고 있다.', ant:'-', frm:'-'},
    {id:'desdetiemposancestrales',   t:'expr', w:'desde tiempos ancestrales',  m:'먼 옛날부터',         ee:'Desde tiempos ancestrales, esta tierra fue sagrada.',          ek:'먼 옛날부터 이 땅은 신성시되었다.',    ant:'-', frm:'-'},
  ]
};
